2023-04-09 12:35:47,745 INFO     > Lancement de l'application ! 
2023-04-09 12:35:47,745 INFO     > Création de la base de donnée
2023-04-09 12:35:47,746 INFO     > Démarrage du serveur flask
2023-04-09 12:37:20,649 DEBUG    > Requête index.html
2023-04-09 12:41:35,842 DEBUG    > Requête signup.html
2023-04-09 12:53:23,735 INFO     > Lancement de l'application ! 
2023-04-09 12:53:23,735 INFO     > Création de la base de donnée
2023-04-09 12:53:23,740 INFO     > Démarrage du serveur flask
2023-04-09 12:54:25,302 DEBUG    > Requête signup.html
2023-04-09 12:55:40,314 DEBUG    > Requête signup.html
2023-04-09 12:56:40,350 INFO     > Lancement de l'application ! 
2023-04-09 12:56:40,351 INFO     > Création de la base de donnée
2023-04-09 12:56:40,352 INFO     > Démarrage du serveur flask
2023-04-09 12:56:42,401 DEBUG    > Requête signup.html
2023-04-09 12:58:37,185 DEBUG    > Requête signup.html
2023-04-09 12:58:46,902 DEBUG    > Requête api_signup
2023-04-09 12:58:46,902 DEBUG    > Email déja existant
2023-04-09 12:59:05,361 INFO     > Lancement de l'application ! 
2023-04-09 12:59:05,361 INFO     > Création de la base de donnée
2023-04-09 12:59:05,367 INFO     > Démarrage du serveur flask
2023-04-09 12:59:05,712 DEBUG    > Requête signup.html
2023-04-09 12:59:07,080 DEBUG    > Requête signup.html
2023-04-09 12:59:14,219 DEBUG    > Requête api_signup
2023-04-09 12:59:14,220 DEBUG    > Email déja existant
2023-04-09 13:02:44,388 INFO     > Lancement de l'application ! 
2023-04-09 13:02:44,389 INFO     > Création de la base de donnée
2023-04-09 13:02:44,389 INFO     > Démarrage du serveur flask
2023-04-09 13:02:46,426 DEBUG    > Requête signup.html
2023-04-09 13:02:57,220 DEBUG    > Requête api_signup
2023-04-09 13:02:57,221 ERROR    > Erreur inconnue dans la fonction signup
2023-04-09 13:02:57,222 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\lib\sign.py", line 11, in signup
    res,err = mydb.read_row("users",f"user = '{payload['user']}'")
KeyError: 'user'

2023-04-09 13:04:02,662 INFO     > Lancement de l'application ! 
2023-04-09 13:04:02,662 INFO     > Création de la base de donnée
2023-04-09 13:04:02,663 INFO     > Démarrage du serveur flask
2023-04-09 13:04:04,754 DEBUG    > Requête signup.html
2023-04-09 13:04:12,619 DEBUG    > Requête api_signup
2023-04-09 13:04:12,624 INFO     > Compte créé : Noan
2023-04-09 13:04:15,087 DEBUG    > Requête signin.html
2023-04-09 13:17:19,503 INFO     > Lancement de l'application ! 
2023-04-09 13:17:19,503 INFO     > Création de la base de donnée
2023-04-09 13:17:19,508 INFO     > Démarrage du serveur flask
2023-04-09 13:17:19,789 DEBUG    > Requête signin.html
2023-04-09 13:17:22,101 DEBUG    > Requête signup.html
2023-04-09 13:17:32,583 DEBUG    > Requête api_signup
2023-04-09 13:17:32,589 INFO     > Compte créé : Noan
2023-04-09 13:17:34,442 DEBUG    > Requête signin.html
2023-04-09 13:18:42,156 DEBUG    > Requête signin.html
2023-04-09 13:19:50,929 INFO     > Lancement de l'application ! 
2023-04-09 13:19:50,930 INFO     > Création de la base de donnée
2023-04-09 13:19:50,930 INFO     > Démarrage du serveur flask
2023-04-09 13:19:53,157 DEBUG    > Requête signin.html
2023-04-09 13:19:58,450 DEBUG    > Requête api_signin
2023-04-09 13:19:58,450 ERROR    > Erreur inconnue dans api_signin
2023-04-09 13:19:58,451 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 117, in api_signin
    result,session = sign.signin(logger=logger,mydb=mydb,payload=request.json,debug=debug,session=session)
UnboundLocalError: local variable 'session' referenced before assignment

2023-04-09 13:55:59,734 INFO     > Lancement de l'application ! 
2023-04-09 13:55:59,734 INFO     > Création de la base de donnée
2023-04-09 13:55:59,735 INFO     > Démarrage du serveur flask
2023-04-09 13:56:03,410 DEBUG    > Requête signin.html
2023-04-09 13:56:08,833 DEBUG    > Requête api_signin
2023-04-09 13:56:08,834 DEBUG    > Mot de passe incorect
2023-04-09 13:56:19,561 DEBUG    > Requête api_signin
2023-04-09 13:56:19,562 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 13:56:21,528 DEBUG    > Requête index.html
2023-04-09 14:01:27,112 INFO     > Lancement de l'application ! 
2023-04-09 14:01:27,112 INFO     > Création de la base de donnée
2023-04-09 14:01:27,113 INFO     > Démarrage du serveur flask
2023-04-09 14:01:31,402 DEBUG    > Requête signin.html
2023-04-09 14:01:35,251 DEBUG    > Requête signup.html
2023-04-09 14:01:37,395 DEBUG    > Requête signin.html
2023-04-09 14:01:42,676 DEBUG    > Requête index.html
2023-04-09 14:13:16,880 DEBUG    > Requête index.html
2023-04-09 14:13:18,458 DEBUG    > Requête signin.html
2023-04-09 14:13:20,143 DEBUG    > Requête signup.html
2023-04-09 14:14:40,313 DEBUG    > Requête signup.html
2023-04-09 14:15:12,511 DEBUG    > Requête signup.html
2023-04-09 14:16:10,947 DEBUG    > Requête signup.html
2023-04-09 14:16:49,091 DEBUG    > Requête signup.html
2023-04-09 14:17:42,693 DEBUG    > Requête signup.html
2023-04-09 14:18:00,065 DEBUG    > Requête signup.html
2023-04-09 14:18:22,579 DEBUG    > Requête signup.html
2023-04-09 14:19:02,835 DEBUG    > Requête signup.html
2023-04-09 14:19:17,848 DEBUG    > Requête signup.html
2023-04-09 14:19:37,160 DEBUG    > Requête signup.html
2023-04-09 14:20:09,219 DEBUG    > Requête signup.html
2023-04-09 14:20:30,926 DEBUG    > Requête signup.html
2023-04-09 14:21:04,915 DEBUG    > Requête signup.html
2023-04-09 14:21:50,894 DEBUG    > Requête signup.html
2023-04-09 14:22:16,431 DEBUG    > Requête signup.html
2023-04-09 14:22:31,972 DEBUG    > Requête signup.html
2023-04-09 14:22:50,889 DEBUG    > Requête signup.html
2023-04-09 14:23:02,854 DEBUG    > Requête signup.html
2023-04-09 14:23:38,896 DEBUG    > Requête signup.html
2023-04-09 14:24:09,034 DEBUG    > Requête signup.html
2023-04-09 14:24:31,399 DEBUG    > Requête signup.html
2023-04-09 14:24:41,635 DEBUG    > Requête signup.html
2023-04-09 14:24:52,470 DEBUG    > Requête signup.html
2023-04-09 14:24:59,424 DEBUG    > Requête signup.html
2023-04-09 14:25:14,957 DEBUG    > Requête signup.html
2023-04-09 14:26:24,455 DEBUG    > Requête api_signup
2023-04-09 14:26:24,463 INFO     > Compte créé : David
2023-04-09 14:26:26,070 DEBUG    > Requête signin.html
2023-04-09 14:26:30,118 DEBUG    > Requête signup.html
2023-04-09 14:27:40,013 DEBUG    > Requête api_signup
2023-04-09 14:27:40,014 DEBUG    > Email déja existant
2023-04-09 14:29:50,399 DEBUG    > Requête signup.html
2023-04-09 14:30:07,519 DEBUG    > Requête api_signup
2023-04-09 14:30:07,519 DEBUG    > Email déja existant
2023-04-09 14:30:30,715 DEBUG    > Requête signin.html
2023-04-09 14:31:01,885 DEBUG    > Requête signin.html
2023-04-09 14:31:22,394 DEBUG    > Requête signin.html
2023-04-09 14:31:24,250 DEBUG    > Requête signin.html
2023-04-09 14:31:27,511 DEBUG    > Requête signin.html
2023-04-09 14:31:33,775 DEBUG    > Requête signup.html
2023-04-09 14:32:12,237 DEBUG    > Requête signup.html
2023-04-09 14:32:32,962 DEBUG    > Requête signup.html
2023-04-09 14:32:57,095 DEBUG    > Requête signup.html
2023-04-09 14:33:30,178 DEBUG    > Requête signup.html
2023-04-09 14:33:37,639 DEBUG    > Requête signin.html
2023-04-09 14:33:39,006 DEBUG    > Requête api_signin
2023-04-09 14:33:39,006 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:35:10,565 DEBUG    > Requête signin.html
2023-04-09 14:35:11,812 DEBUG    > Requête api_signin
2023-04-09 14:35:11,812 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:35:26,299 DEBUG    > Requête signin.html
2023-04-09 14:35:27,573 DEBUG    > Requête api_signin
2023-04-09 14:35:27,573 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:35:33,561 DEBUG    > Requête signin.html
2023-04-09 14:35:35,133 DEBUG    > Requête api_signin
2023-04-09 14:35:35,134 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:35:57,043 DEBUG    > Requête signin.html
2023-04-09 14:35:58,391 DEBUG    > Requête api_signin
2023-04-09 14:35:58,392 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:36:06,149 DEBUG    > Requête signin.html
2023-04-09 14:36:16,341 DEBUG    > Requête signin.html
2023-04-09 14:36:17,484 DEBUG    > Requête api_signin
2023-04-09 14:36:17,485 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:40:12,516 DEBUG    > Requête signin.html
2023-04-09 14:40:20,856 DEBUG    > Requête api_signin
2023-04-09 14:40:20,857 DEBUG    > Mot de passe incorect
2023-04-09 14:40:34,780 DEBUG    > Requête api_signin
2023-04-09 14:40:34,780 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:40:52,138 DEBUG    > Requête api_signin
2023-04-09 14:40:52,138 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:41:38,735 DEBUG    > Requête signin.html
2023-04-09 14:41:46,053 DEBUG    > Requête api_signin
2023-04-09 14:41:46,054 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:42:58,844 DEBUG    > Requête signin.html
2023-04-09 14:43:02,758 DEBUG    > Requête api_signin
2023-04-09 14:43:02,759 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:43:13,341 DEBUG    > Requête signin.html
2023-04-09 14:43:16,921 DEBUG    > Requête api_signin
2023-04-09 14:43:16,921 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:43:33,561 DEBUG    > Requête api_signin
2023-04-09 14:43:33,561 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:43:49,112 DEBUG    > Requête api_signin
2023-04-09 14:43:49,112 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:43:51,500 DEBUG    > Requête signin.html
2023-04-09 14:43:57,617 DEBUG    > Requête api_signin
2023-04-09 14:43:57,617 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:44:47,419 DEBUG    > Requête signin.html
2023-04-09 14:44:56,004 DEBUG    > Requête api_signin
2023-04-09 14:44:56,005 DEBUG    > Mot de passe incorect
2023-04-09 14:45:14,748 DEBUG    > Requête signin.html
2023-04-09 14:45:17,855 DEBUG    > Requête api_signin
2023-04-09 14:45:17,855 DEBUG    > Mot de passe incorect
2023-04-09 14:46:06,192 DEBUG    > Requête signin.html
2023-04-09 14:46:10,166 DEBUG    > Requête api_signin
2023-04-09 14:46:10,168 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:46:29,799 DEBUG    > Requête signin.html
2023-04-09 14:46:34,418 DEBUG    > Requête api_signin
2023-04-09 14:46:34,419 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:47:08,285 DEBUG    > Requête signin.html
2023-04-09 14:47:17,060 DEBUG    > Requête api_signin
2023-04-09 14:47:17,061 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:47:23,792 DEBUG    > Requête signin.html
2023-04-09 14:47:27,825 DEBUG    > Requête api_signin
2023-04-09 14:47:27,825 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:47:35,105 DEBUG    > Requête signin.html
2023-04-09 14:47:38,058 DEBUG    > Requête api_signin
2023-04-09 14:47:38,059 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:47:42,498 DEBUG    > Requête signin.html
2023-04-09 14:47:45,943 DEBUG    > Requête api_signin
2023-04-09 14:47:45,943 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:47:49,601 DEBUG    > Requête api_signin
2023-04-09 14:47:49,602 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 14:47:50,901 DEBUG    > Requête signin.html
2023-04-09 14:48:25,999 DEBUG    > Requête signin.html
2023-04-09 14:48:26,882 DEBUG    > Requête index.html
2023-04-09 14:48:31,927 DEBUG    > Requête signup.html
2023-04-09 14:48:33,858 DEBUG    > Requête signin.html
2023-04-09 14:48:41,448 DEBUG    > Requête api_signin
2023-04-09 14:48:41,448 INFO     > Autentification validé pour : door7302@gmail.com
2023-04-09 14:48:41,478 DEBUG    > Requête index.html
2023-04-09 14:48:49,761 DEBUG    > Requête signin.html
2023-04-09 14:50:19,889 DEBUG    > Requête signin.html
2023-04-09 14:53:49,302 DEBUG    > Requête signup.html
2023-04-09 14:53:54,682 DEBUG    > Requête signin.html
2023-04-09 14:54:33,032 DEBUG    > Requête index.html
2023-04-09 14:55:03,491 DEBUG    > Requête index.html
2023-04-09 14:55:24,956 DEBUG    > Requête projet.html
2023-04-09 14:55:27,758 DEBUG    > Requête index.html
2023-04-09 14:55:29,298 DEBUG    > Requête projet.html
2023-04-09 14:55:31,058 DEBUG    > Requête signin.html
2023-04-09 14:55:32,104 DEBUG    > Requête index.html
2023-04-09 14:55:50,411 DEBUG    > Requête projet.html
2023-04-09 14:55:51,713 DEBUG    > Requête signin.html
2023-04-09 14:55:54,686 DEBUG    > Requête index.html
2023-04-09 14:58:59,193 DEBUG    > Requête projet.html
2023-04-09 14:59:00,084 DEBUG    > Requête index.html
2023-04-09 14:59:00,626 DEBUG    > Requête projet.html
2023-04-09 14:59:01,058 DEBUG    > Requête index.html
2023-04-09 14:59:01,484 DEBUG    > Requête projet.html
2023-04-09 14:59:01,862 DEBUG    > Requête index.html
2023-04-09 14:59:02,732 DEBUG    > Requête index.html
2023-04-09 14:59:03,755 DEBUG    > Requête projet.html
2023-04-09 14:59:05,238 DEBUG    > Requête projet.html
2023-04-09 14:59:05,664 DEBUG    > Requête index.html
2023-04-09 14:59:06,342 DEBUG    > Requête projet.html
2023-04-09 14:59:07,582 DEBUG    > Requête signup.html
2023-04-09 14:59:14,183 DEBUG    > Requête index.html
2023-04-09 14:59:29,322 DEBUG    > Requête signup.html
2023-04-09 14:59:32,223 DEBUG    > Requête index.html
2023-04-09 15:00:17,425 DEBUG    > Requête index.html
2023-04-09 15:01:13,138 DEBUG    > Requête index.html
2023-04-09 15:01:34,737 DEBUG    > Requête index.html
2023-04-09 15:02:33,035 DEBUG    > Requête index.html
2023-04-09 15:02:39,514 DEBUG    > Requête index.html
2023-04-09 15:04:23,720 DEBUG    > Requête index.html
2023-04-09 15:04:54,339 DEBUG    > Requête index.html
2023-04-09 15:05:13,079 DEBUG    > Requête index.html
2023-04-09 15:07:57,556 DEBUG    > Requête index.html
2023-04-09 15:08:35,996 DEBUG    > Requête index.html
2023-04-09 15:09:02,452 DEBUG    > Requête index.html
2023-04-09 15:09:31,695 DEBUG    > Requête index.html
2023-04-09 15:09:39,989 DEBUG    > Requête index.html
2023-04-09 15:09:47,982 DEBUG    > Requête index.html
2023-04-09 15:09:50,198 DEBUG    > Requête projet.html
2023-04-09 15:09:53,632 DEBUG    > Requête index.html
2023-04-09 15:10:08,839 DEBUG    > Requête index.html
2023-04-09 15:10:16,992 DEBUG    > Requête index.html
2023-04-09 15:10:28,780 DEBUG    > Requête index.html
2023-04-09 15:11:21,258 DEBUG    > Requête index.html
2023-04-09 15:11:27,415 DEBUG    > Requête index.html
2023-04-09 15:12:24,598 DEBUG    > Requête index.html
2023-04-09 15:12:51,648 DEBUG    > Requête index.html
2023-04-09 15:13:03,010 DEBUG    > Requête index.html
2023-04-09 15:13:18,987 DEBUG    > Requête index.html
2023-04-09 15:13:26,465 DEBUG    > Requête index.html
2023-04-09 15:13:51,781 DEBUG    > Requête index.html
2023-04-09 15:14:26,746 DEBUG    > Requête index.html
2023-04-09 15:14:33,519 DEBUG    > Requête index.html
2023-04-09 15:15:02,145 DEBUG    > Requête index.html
2023-04-09 15:15:56,922 DEBUG    > Requête index.html
2023-04-09 15:16:03,665 DEBUG    > Requête index.html
2023-04-09 15:16:11,763 DEBUG    > Requête index.html
2023-04-09 15:17:03,107 DEBUG    > Requête index.html
2023-04-09 15:17:20,629 DEBUG    > Requête index.html
2023-04-09 15:17:28,076 DEBUG    > Requête index.html
2023-04-09 15:17:40,168 DEBUG    > Requête index.html
2023-04-09 15:17:57,326 DEBUG    > Requête index.html
2023-04-09 15:18:03,591 DEBUG    > Requête index.html
2023-04-09 15:18:17,518 DEBUG    > Requête index.html
2023-04-09 15:18:33,968 DEBUG    > Requête index.html
2023-04-09 15:18:37,511 DEBUG    > Requête perso.html
2023-04-09 15:18:41,123 DEBUG    > Requête index.html
2023-04-09 15:18:47,732 DEBUG    > Requête index.html
2023-04-09 15:19:05,000 DEBUG    > Requête perso.html
2023-04-09 15:19:07,286 DEBUG    > Requête index.html
2023-04-09 15:19:47,585 DEBUG    > Requête index.html
2023-04-09 15:20:14,943 DEBUG    > Requête index.html
2023-04-09 15:20:26,938 DEBUG    > Requête index.html
2023-04-09 15:20:42,799 DEBUG    > Requête index.html
2023-04-09 15:20:56,056 DEBUG    > Requête index.html
2023-04-09 15:21:05,632 DEBUG    > Requête index.html
2023-04-09 15:21:16,297 DEBUG    > Requête index.html
2023-04-09 15:21:23,840 DEBUG    > Requête index.html
2023-04-09 15:21:31,357 DEBUG    > Requête index.html
2023-04-09 15:21:57,707 DEBUG    > Requête index.html
2023-04-09 15:22:27,712 DEBUG    > Requête index.html
2023-04-09 15:22:40,731 DEBUG    > Requête index.html
2023-04-09 15:24:39,336 DEBUG    > Requête index.html
2023-04-09 15:24:49,763 DEBUG    > Requête index.html
2023-04-09 15:25:51,775 DEBUG    > Requête index.html
2023-04-09 15:25:59,885 DEBUG    > Requête index.html
2023-04-09 15:26:12,777 DEBUG    > Requête index.html
2023-04-09 15:26:36,054 DEBUG    > Requête index.html
2023-04-09 15:26:55,370 DEBUG    > Requête index.html
2023-04-09 15:27:10,513 DEBUG    > Requête index.html
2023-04-09 15:27:31,121 DEBUG    > Requête index.html
2023-04-09 15:27:45,990 DEBUG    > Requête index.html
2023-04-09 15:27:50,615 DEBUG    > Requête index.html
2023-04-09 15:28:15,805 DEBUG    > Requête index.html
2023-04-09 15:28:26,698 DEBUG    > Requête index.html
2023-04-09 15:28:43,855 DEBUG    > Requête index.html
2023-04-09 15:29:07,634 DEBUG    > Requête index.html
2023-04-09 15:29:17,141 DEBUG    > Requête index.html
2023-04-09 15:29:26,818 DEBUG    > Requête index.html
2023-04-09 15:30:13,722 DEBUG    > Requête index.html
2023-04-09 15:31:15,658 DEBUG    > Requête index.html
2023-04-09 15:32:01,764 DEBUG    > Requête index.html
2023-04-09 15:32:46,921 DEBUG    > Requête index.html
2023-04-09 15:33:58,755 DEBUG    > Requête index.html
2023-04-09 15:34:20,745 DEBUG    > Requête index.html
2023-04-09 15:34:32,228 DEBUG    > Requête projet.html
2023-04-09 15:34:38,190 DEBUG    > Requête index.html
2023-04-09 15:34:40,104 DEBUG    > Requête perso.html
2023-04-09 15:35:46,900 DEBUG    > Requête perso.html
2023-04-09 15:36:38,772 DEBUG    > Requête index.html
2023-04-09 15:37:28,202 DEBUG    > Requête index.html
2023-04-09 15:38:16,112 DEBUG    > Requête perso.html
2023-04-09 15:38:25,218 DEBUG    > Requête index.html
2023-04-09 16:06:29,415 DEBUG    > Requête index.html
2023-04-09 16:14:23,037 DEBUG    > Requête index.html
2023-04-09 16:15:15,477 DEBUG    > Requête index.html
2023-04-09 16:15:24,185 INFO     > Lancement de l'application ! 
2023-04-09 16:15:24,185 INFO     > Création de la base de donnée
2023-04-09 16:15:24,186 INFO     > Démarrage du serveur flask
2023-04-09 16:15:26,340 DEBUG    > Requête index.html
2023-04-09 16:15:29,424 DEBUG    > Requête profil.html
2023-04-09 16:18:00,640 DEBUG    > Requête index.html
2023-04-09 16:18:03,506 DEBUG    > Requête profil.html
2023-04-09 16:18:36,901 DEBUG    > Requête profil.html
2023-04-09 16:18:54,624 DEBUG    > Requête profil.html
2023-04-09 16:19:04,020 DEBUG    > Requête profil.html
2023-04-09 16:19:29,471 DEBUG    > Requête profil.html
2023-04-09 16:19:39,844 DEBUG    > Requête profil.html
2023-04-09 16:19:47,435 DEBUG    > Requête profil.html
2023-04-09 16:20:53,942 DEBUG    > Requête profil.html
2023-04-09 16:21:00,729 DEBUG    > Requête profil.html
2023-04-09 16:21:10,685 DEBUG    > Requête profil.html
2023-04-09 16:21:26,473 DEBUG    > Requête profil.html
2023-04-09 16:21:40,286 DEBUG    > Requête profil.html
2023-04-09 16:21:48,690 DEBUG    > Requête profil.html
2023-04-09 16:22:06,513 DEBUG    > Requête profil.html
2023-04-09 16:22:16,329 DEBUG    > Requête profil.html
2023-04-09 16:23:03,012 DEBUG    > Requête profil.html
2023-04-09 16:24:01,553 DEBUG    > Requête profil.html
2023-04-09 16:24:11,507 DEBUG    > Requête profil.html
2023-04-09 16:24:31,715 DEBUG    > Requête profil.html
2023-04-09 16:24:34,717 DEBUG    > Requête profil.html
2023-04-09 16:26:32,345 DEBUG    > Requête profil.html
2023-04-09 16:26:44,446 DEBUG    > Requête profil.html
2023-04-09 16:26:53,826 DEBUG    > Requête profil.html
2023-04-09 16:27:01,047 DEBUG    > Requête profil.html
2023-04-09 16:27:23,733 DEBUG    > Requête profil.html
2023-04-09 16:27:58,475 DEBUG    > Requête profil.html
2023-04-09 16:28:10,564 DEBUG    > Requête profil.html
2023-04-09 16:28:37,858 DEBUG    > Requête profil.html
2023-04-09 16:29:18,088 DEBUG    > Requête profil.html
2023-04-09 16:29:33,749 DEBUG    > Requête profil.html
2023-04-09 16:29:55,017 DEBUG    > Requête profil.html
2023-04-09 16:32:08,203 DEBUG    > Requête profil.html
2023-04-09 16:32:13,614 DEBUG    > Requête profil.html
2023-04-09 16:32:43,643 DEBUG    > Requête profil.html
2023-04-09 16:32:46,039 DEBUG    > Requête profil.html
2023-04-09 16:33:40,121 DEBUG    > Requête profil.html
2023-04-09 16:53:50,926 DEBUG    > Requête profil.html
2023-04-09 16:53:56,030 DEBUG    > Requête index.html
2023-04-09 16:54:00,082 DEBUG    > Requête projet.html
2023-04-09 16:54:03,687 DEBUG    > Requête index.html
2023-04-09 16:55:20,688 DEBUG    > Requête profil.html
2023-04-09 16:55:23,057 DEBUG    > Requête index.html
2023-04-09 16:58:34,913 DEBUG    > Requête index.html
2023-04-09 16:58:40,715 DEBUG    > Requête projet.html
2023-04-09 16:58:41,997 DEBUG    > Requête signin.html
2023-04-09 16:58:47,229 DEBUG    > Requête api_signin
2023-04-09 16:58:47,230 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 16:59:43,895 DEBUG    > Requête signin.html
2023-04-09 17:00:44,651 DEBUG    > Requête signin.html
2023-04-09 17:00:53,829 DEBUG    > Requête api_signin
2023-04-09 17:00:53,829 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 17:00:55,350 DEBUG    > Requête api_signin
2023-04-09 17:00:55,351 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 17:00:56,904 DEBUG    > Requête api_signin
2023-04-09 17:00:56,905 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 17:02:59,512 DEBUG    > Requête signin.html
2023-04-09 17:03:04,688 DEBUG    > Requête api_signin
2023-04-09 17:03:04,689 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 17:03:55,565 DEBUG    > Requête signin.html
2023-04-09 17:04:01,287 DEBUG    > Requête api_signin
2023-04-09 17:04:01,287 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 17:04:03,706 DEBUG    > Requête index.html
2023-04-09 17:07:38,187 DEBUG    > Requête index.html
2023-04-09 17:07:41,153 DEBUG    > Requête projet.html
2023-04-09 17:07:43,464 DEBUG    > Requête signin.html
2023-04-09 17:07:49,097 DEBUG    > Requête api_signin
2023-04-09 17:07:49,097 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 17:07:50,333 DEBUG    > Requête index.html
2023-04-09 17:36:10,899 INFO     > Lancement de l'application ! 
2023-04-09 17:36:10,900 INFO     > Création de la base de donnée
2023-04-09 17:36:10,900 INFO     > Démarrage du serveur flask
2023-04-09 17:36:16,492 DEBUG    > Requête index.html
2023-04-09 17:36:18,550 DEBUG    > Requête projet.html
2023-04-09 17:36:20,722 DEBUG    > Requête signin.html
2023-04-09 17:36:29,985 DEBUG    > Requête api_signin
2023-04-09 17:36:29,986 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:36:29,986 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 139, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,payload=request.json,debug=debug,session=mySession)
TypeError: signin() got an unexpected keyword argument 'session'

2023-04-09 17:36:38,884 DEBUG    > Requête api_signin
2023-04-09 17:36:38,885 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:36:38,885 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 139, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,payload=request.json,debug=debug,session=mySession)
TypeError: signin() got an unexpected keyword argument 'session'

2023-04-09 17:36:39,601 DEBUG    > Requête api_signin
2023-04-09 17:36:39,602 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:36:39,602 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 139, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,payload=request.json,debug=debug,session=mySession)
TypeError: signin() got an unexpected keyword argument 'session'

2023-04-09 17:43:52,639 INFO     > Lancement de l'application ! 
2023-04-09 17:43:52,640 INFO     > Création de la base de donnée
2023-04-09 17:43:52,640 INFO     > Démarrage du serveur flask
2023-04-09 17:43:56,832 DEBUG    > Requête signin.html
2023-04-09 17:44:05,154 DEBUG    > Requête api_signin
2023-04-09 17:44:05,155 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:44:05,172 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 139, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:45:18,855 INFO     > Lancement de l'application ! 
2023-04-09 17:45:18,856 INFO     > Création de la base de donnée
2023-04-09 17:45:18,856 INFO     > Démarrage du serveur flask
2023-04-09 17:45:21,560 DEBUG    > Requête api_signin
2023-04-09 17:45:21,563 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:45:21,564 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:45:22,651 DEBUG    > Requête signin.html
2023-04-09 17:45:27,275 DEBUG    > Requête api_signin
2023-04-09 17:45:27,276 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:45:27,276 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:45:41,580 INFO     > Lancement de l'application ! 
2023-04-09 17:45:41,580 INFO     > Création de la base de donnée
2023-04-09 17:45:41,581 INFO     > Démarrage du serveur flask
2023-04-09 17:45:44,575 DEBUG    > Requête signin.html
2023-04-09 17:45:49,092 DEBUG    > Requête api_signin
2023-04-09 17:45:49,093 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:45:49,095 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:47:24,160 INFO     > Lancement de l'application ! 
2023-04-09 17:47:24,160 INFO     > Création de la base de donnée
2023-04-09 17:47:24,161 INFO     > Démarrage du serveur flask
2023-04-09 17:47:25,836 DEBUG    > Requête api_signin
2023-04-09 17:47:25,836 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:47:25,838 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:47:27,466 DEBUG    > Requête signin.html
2023-04-09 17:47:33,143 DEBUG    > Requête api_signin
2023-04-09 17:47:33,144 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:47:33,144 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:47:35,154 DEBUG    > Requête signin.html
2023-04-09 17:47:37,433 DEBUG    > Requête signin.html
2023-04-09 17:47:42,969 DEBUG    > Requête api_signin
2023-04-09 17:47:42,969 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:47:42,970 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:48:57,827 DEBUG    > Requête signin.html
2023-04-09 17:48:58,711 DEBUG    > Requête signin.html
2023-04-09 17:49:05,197 DEBUG    > Requête signup.html
2023-04-09 17:49:06,952 DEBUG    > Requête signin.html
2023-04-09 17:49:28,437 DEBUG    > Requête signin.html
2023-04-09 17:50:09,695 DEBUG    > Requête signin.html
2023-04-09 17:50:11,375 DEBUG    > Requête signin.html
2023-04-09 17:50:39,463 DEBUG    > Requête signin.html
2023-04-09 17:50:41,042 DEBUG    > Requête signin.html
2023-04-09 17:51:15,873 DEBUG    > Requête signin.html
2023-04-09 17:51:17,071 DEBUG    > Requête signin.html
2023-04-09 17:51:24,622 DEBUG    > Requête signin.html
2023-04-09 17:52:10,522 DEBUG    > Requête signin.html
2023-04-09 17:52:28,260 INFO     > Lancement de l'application ! 
2023-04-09 17:52:28,260 INFO     > Création de la base de donnée
2023-04-09 17:52:28,261 INFO     > Démarrage du serveur flask
2023-04-09 17:52:29,743 DEBUG    > Requête signin.html
2023-04-09 17:52:34,128 DEBUG    > Requête api_signin
2023-04-09 17:52:34,128 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:52:34,131 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug,session=mySession)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:53:33,902 INFO     > Lancement de l'application ! 
2023-04-09 17:53:33,902 INFO     > Création de la base de donnée
2023-04-09 17:53:33,903 INFO     > Démarrage du serveur flask
2023-04-09 17:53:35,709 DEBUG    > Requête signin.html
2023-04-09 17:53:37,382 DEBUG    > Requête signin.html
2023-04-09 17:53:42,170 DEBUG    > Requête api_signin
2023-04-09 17:53:42,171 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:53:42,174 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:54:41,992 DEBUG    > Requête signin.html
2023-04-09 17:54:42,843 DEBUG    > Requête signin.html
2023-04-09 17:54:45,969 INFO     > Lancement de l'application ! 
2023-04-09 17:54:45,970 INFO     > Création de la base de donnée
2023-04-09 17:54:45,972 INFO     > Démarrage du serveur flask
2023-04-09 17:54:47,352 DEBUG    > Requête signin.html
2023-04-09 17:54:52,431 DEBUG    > Requête api_signin
2023-04-09 17:54:52,432 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:54:52,435 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.json['email'],pwd=request.json['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:55:30,195 INFO     > Lancement de l'application ! 
2023-04-09 17:55:30,195 INFO     > Création de la base de donnée
2023-04-09 17:55:30,196 INFO     > Démarrage du serveur flask
2023-04-09 17:55:31,713 DEBUG    > Requête signin.html
2023-04-09 17:55:32,581 DEBUG    > Requête signin.html
2023-04-09 17:55:38,164 DEBUG    > Requête api_signin
2023-04-09 17:55:38,164 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:55:38,165 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 139, in api_signin
    print (request.form + "a")
TypeError: unsupported operand type(s) for +: 'ImmutableMultiDict' and 'str'

2023-04-09 17:56:03,015 DEBUG    > Requête signin.html
2023-04-09 17:56:05,090 DEBUG    > Requête signin.html
2023-04-09 17:56:12,714 DEBUG    > Requête api_signin
2023-04-09 17:56:12,714 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:56:12,715 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 139, in api_signin
    print (str(request.form) + "a")
TypeError: unsupported operand type(s) for +: 'ImmutableMultiDict' and 'str'

2023-04-09 17:56:24,163 DEBUG    > Requête signin.html
2023-04-09 17:56:32,035 INFO     > Lancement de l'application ! 
2023-04-09 17:56:32,035 INFO     > Création de la base de donnée
2023-04-09 17:56:32,036 INFO     > Démarrage du serveur flask
2023-04-09 17:56:38,148 DEBUG    > Requête api_signin
2023-04-09 17:56:38,148 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:56:38,150 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.json['email'],pwd=request.json['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:56:55,395 DEBUG    > Requête signin.html
2023-04-09 17:56:58,972 INFO     > Lancement de l'application ! 
2023-04-09 17:56:58,973 INFO     > Création de la base de donnée
2023-04-09 17:56:58,973 INFO     > Démarrage du serveur flask
2023-04-09 17:57:00,749 DEBUG    > Requête signin.html
2023-04-09 17:57:06,439 DEBUG    > Requête api_signin
2023-04-09 17:57:06,439 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:57:06,441 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 139, in api_signin
    print (request.json)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:57:19,187 INFO     > Lancement de l'application ! 
2023-04-09 17:57:19,187 INFO     > Création de la base de donnée
2023-04-09 17:57:19,188 INFO     > Démarrage du serveur flask
2023-04-09 17:57:20,264 DEBUG    > Requête signin.html
2023-04-09 17:57:25,653 DEBUG    > Requête api_signin
2023-04-09 17:57:25,654 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:57:25,656 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.json['email'],pwd=request.json['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:58:16,132 DEBUG    > Requête signin.html
2023-04-09 17:58:26,345 INFO     > Lancement de l'application ! 
2023-04-09 17:58:26,345 INFO     > Création de la base de donnée
2023-04-09 17:58:26,346 INFO     > Démarrage du serveur flask
2023-04-09 17:58:28,235 DEBUG    > Requête signin.html
2023-04-09 17:58:33,262 DEBUG    > Requête api_signin
2023-04-09 17:58:33,266 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:58:33,267 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 17:59:26,419 INFO     > Lancement de l'application ! 
2023-04-09 17:59:26,419 INFO     > Création de la base de donnée
2023-04-09 17:59:26,420 INFO     > Démarrage du serveur flask
2023-04-09 17:59:28,119 DEBUG    > Requête signin.html
2023-04-09 17:59:30,051 DEBUG    > Requête signin.html
2023-04-09 17:59:35,502 DEBUG    > Requête api_signin
2023-04-09 17:59:35,502 ERROR    > Erreur inconnue dans api_signin
2023-04-09 17:59:35,504 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 141, in api_signin
    result, user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:01:32,630 INFO     > Lancement de l'application ! 
2023-04-09 18:01:32,630 INFO     > Création de la base de donnée
2023-04-09 18:01:32,631 INFO     > Démarrage du serveur flask
2023-04-09 18:01:34,265 DEBUG    > Requête signin.html
2023-04-09 18:01:36,378 DEBUG    > Requête signin.html
2023-04-09 18:01:41,747 DEBUG    > Requête api_signin
2023-04-09 18:01:41,748 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:01:41,750 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 141, in api_signin
    result,user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:02:14,361 INFO     > Lancement de l'application ! 
2023-04-09 18:02:14,361 INFO     > Création de la base de donnée
2023-04-09 18:02:14,362 INFO     > Démarrage du serveur flask
2023-04-09 18:02:16,038 DEBUG    > Requête signin.html
2023-04-09 18:02:17,033 DEBUG    > Requête signin.html
2023-04-09 18:02:22,497 DEBUG    > Requête api_signin
2023-04-09 18:02:22,497 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:02:22,499 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 141, in api_signin
    result,user = sign.signin(logger=logger,mydb=mydb,email=request.form['email'],pwd=request.form['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:02:43,813 INFO     > Lancement de l'application ! 
2023-04-09 18:02:43,813 INFO     > Création de la base de donnée
2023-04-09 18:02:43,814 INFO     > Démarrage du serveur flask
2023-04-09 18:02:45,656 DEBUG    > Requête signin.html
2023-04-09 18:02:51,137 DEBUG    > Requête api_signin
2023-04-09 18:02:51,138 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:02:51,139 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 141, in api_signin
    result,user = sign.signin(logger=logger,mydb=mydb,email="roynoan",pwd=request.form['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:03:03,443 INFO     > Lancement de l'application ! 
2023-04-09 18:03:03,443 INFO     > Création de la base de donnée
2023-04-09 18:03:03,444 INFO     > Démarrage du serveur flask
2023-04-09 18:03:04,987 DEBUG    > Requête signin.html
2023-04-09 18:03:09,548 DEBUG    > Requête api_signin
2023-04-09 18:03:09,548 ERROR    > Erreur inconnue dans la fonction signin
2023-04-09 18:03:09,549 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:03:09,549 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 145, in api_signin
    return resp
UnboundLocalError: local variable 'resp' referenced before assignment

2023-04-09 18:03:48,158 DEBUG    > Requête signin.html
2023-04-09 18:03:56,995 INFO     > Lancement de l'application ! 
2023-04-09 18:03:56,995 INFO     > Création de la base de donnée
2023-04-09 18:03:56,996 INFO     > Démarrage du serveur flask
2023-04-09 18:03:59,641 DEBUG    > Requête signin.html
2023-04-09 18:04:04,825 DEBUG    > Requête api_signin
2023-04-09 18:04:04,826 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:04:04,827 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 141, in api_signin
    result,user = sign.signin(logger=logger,mydb=mydb,email=request.json['email'],pwd=request.json['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:05:12,010 DEBUG    > Requête signin.html
2023-04-09 18:05:18,622 INFO     > Lancement de l'application ! 
2023-04-09 18:05:18,622 INFO     > Création de la base de donnée
2023-04-09 18:05:18,624 INFO     > Démarrage du serveur flask
2023-04-09 18:05:24,594 DEBUG    > Requête api_signin
2023-04-09 18:05:24,595 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:05:24,597 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 141, in api_signin
    result,user = sign.signin(logger=logger,mydb=mydb,email=request.json['email'],pwd=request.json['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:05:39,794 INFO     > Lancement de l'application ! 
2023-04-09 18:05:39,795 INFO     > Création de la base de donnée
2023-04-09 18:05:39,795 INFO     > Démarrage du serveur flask
2023-04-09 18:05:41,235 DEBUG    > Requête signin.html
2023-04-09 18:05:45,154 DEBUG    > Requête api_signin
2023-04-09 18:05:45,155 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:05:45,157 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    print(request.json)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:06:55,379 DEBUG    > Requête signin.html
2023-04-09 18:06:56,345 DEBUG    > Requête signin.html
2023-04-09 18:07:03,064 DEBUG    > Requête api_signin
2023-04-09 18:07:03,064 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:07:03,065 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 140, in api_signin
    print(request.json)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 18:07:30,644 INFO     > Lancement de l'application ! 
2023-04-09 18:07:30,645 INFO     > Création de la base de donnée
2023-04-09 18:07:30,645 INFO     > Démarrage du serveur flask
2023-04-09 18:07:32,548 DEBUG    > Requête signin.html
2023-04-09 18:07:38,839 DEBUG    > Requête api_signin
2023-04-09 18:07:38,840 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:41:59,541 DEBUG    > Requête api_signin
2023-04-09 18:41:59,542 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:42:09,215 INFO     > Lancement de l'application ! 
2023-04-09 18:42:09,215 INFO     > Création de la base de donnée
2023-04-09 18:42:09,216 INFO     > Démarrage du serveur flask
2023-04-09 18:42:10,967 DEBUG    > Requête signin.html
2023-04-09 18:42:16,071 DEBUG    > Requête api_signin
2023-04-09 18:42:16,074 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:51:38,440 INFO     > Lancement de l'application ! 
2023-04-09 18:51:38,441 INFO     > Création de la base de donnée
2023-04-09 18:51:38,441 INFO     > Démarrage du serveur flask
2023-04-09 18:51:40,074 DEBUG    > Requête signin.html
2023-04-09 18:51:42,964 DEBUG    > Requête signin.html
2023-04-09 18:51:44,662 DEBUG    > Requête signin.html
2023-04-09 18:51:46,054 DEBUG    > Requête signin.html
2023-04-09 18:51:47,104 DEBUG    > Requête signin.html
2023-04-09 18:51:50,737 DEBUG    > Requête signin.html
2023-04-09 18:52:15,434 DEBUG    > Requête signin.html
2023-04-09 18:52:16,316 DEBUG    > Requête index.html
2023-04-09 18:53:00,581 INFO     > Lancement de l'application ! 
2023-04-09 18:53:00,581 INFO     > Création de la base de donnée
2023-04-09 18:53:00,582 INFO     > Démarrage du serveur flask
2023-04-09 18:53:03,776 DEBUG    > Requête index.html
2023-04-09 18:53:11,313 DEBUG    > Requête projet.html
2023-04-09 18:53:12,941 DEBUG    > Requête index.html
2023-04-09 18:53:35,939 INFO     > Lancement de l'application ! 
2023-04-09 18:53:35,939 INFO     > Création de la base de donnée
2023-04-09 18:53:35,940 INFO     > Démarrage du serveur flask
2023-04-09 18:53:38,623 DEBUG    > Requête index.html
2023-04-09 18:53:42,746 DEBUG    > Requête projet.html
2023-04-09 18:53:44,524 DEBUG    > Requête index.html
2023-04-09 18:53:54,462 DEBUG    > Requête projet.html
2023-04-09 18:53:56,745 DEBUG    > Requête signin.html
2023-04-09 18:54:05,127 DEBUG    > Requête api_signin
2023-04-09 18:54:05,128 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:54:09,495 DEBUG    > Requête signin.html
2023-04-09 18:54:10,502 DEBUG    > Requête projet.html
2023-04-09 18:54:13,169 DEBUG    > Requête index.html
2023-04-09 18:55:10,539 INFO     > Lancement de l'application ! 
2023-04-09 18:55:10,539 INFO     > Création de la base de donnée
2023-04-09 18:55:10,539 INFO     > Démarrage du serveur flask
2023-04-09 18:55:12,454 DEBUG    > Requête index.html
2023-04-09 18:55:14,936 DEBUG    > Requête projet.html
2023-04-09 18:55:16,567 DEBUG    > Requête signin.html
2023-04-09 18:55:21,449 DEBUG    > Requête api_signin
2023-04-09 18:55:21,451 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:55:40,037 DEBUG    > Requête index.html
2023-04-09 18:55:40,704 DEBUG    > Requête perso.html
2023-04-09 18:55:43,171 DEBUG    > Requête index.html
2023-04-09 18:56:10,047 INFO     > Lancement de l'application ! 
2023-04-09 18:56:10,047 INFO     > Création de la base de donnée
2023-04-09 18:56:10,048 INFO     > Démarrage du serveur flask
2023-04-09 18:56:13,809 DEBUG    > Requête index.html
2023-04-09 18:56:16,207 DEBUG    > Requête projet.html
2023-04-09 18:56:18,512 DEBUG    > Requête signin.html
2023-04-09 18:56:23,680 DEBUG    > Requête api_signin
2023-04-09 18:56:23,681 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:56:23,682 ERROR    > Erreur inconnue dans api_signin
2023-04-09 18:56:23,722 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 146, in api_signin
    resp.set_cookie(user['user'],user['auth'])
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\sansio\response.py", line 230, in set_cookie
    dump_cookie(
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\http.py", line 1213, in dump_cookie
    value = _to_bytes(value, charset)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py", line 107, in _to_bytes
    raise TypeError("Expected bytes")
TypeError: Expected bytes

2023-04-09 18:56:57,783 INFO     > Lancement de l'application ! 
2023-04-09 18:56:57,783 INFO     > Création de la base de donnée
2023-04-09 18:56:57,784 INFO     > Démarrage du serveur flask
2023-04-09 18:57:00,504 DEBUG    > Requête signin.html
2023-04-09 18:57:05,846 DEBUG    > Requête api_signin
2023-04-09 18:57:05,847 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:58:58,250 INFO     > Lancement de l'application ! 
2023-04-09 18:58:58,251 INFO     > Création de la base de donnée
2023-04-09 18:58:58,252 INFO     > Démarrage du serveur flask
2023-04-09 18:59:00,544 DEBUG    > Requête signin.html
2023-04-09 18:59:05,916 DEBUG    > Requête api_signin
2023-04-09 18:59:05,916 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 18:59:13,235 DEBUG    > Requête signin.html
2023-04-09 18:59:13,731 DEBUG    > Requête projet.html
2023-04-09 18:59:15,858 DEBUG    > Requête index.html
2023-04-09 19:01:39,738 DEBUG    > Requête index.html
2023-04-09 19:01:43,513 DEBUG    > Requête projet.html
2023-04-09 19:01:45,395 DEBUG    > Requête signin.html
2023-04-09 19:01:47,259 DEBUG    > Requête signup.html
2023-04-09 19:01:48,827 DEBUG    > Requête signin.html
2023-04-09 19:03:50,770 INFO     > Lancement de l'application ! 
2023-04-09 19:03:50,770 INFO     > Création de la base de donnée
2023-04-09 19:03:50,771 INFO     > Démarrage du serveur flask
2023-04-09 19:03:52,733 DEBUG    > Requête signin.html
2023-04-09 19:03:58,427 DEBUG    > Requête api_signin
2023-04-09 19:03:58,428 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:04:02,409 DEBUG    > Requête index.html
2023-04-09 19:04:35,483 DEBUG    > Requête profil.html
2023-04-09 19:04:37,499 DEBUG    > Requête index.html
2023-04-09 19:04:45,436 DEBUG    > Requête api_signin
2023-04-09 19:04:45,436 ERROR    > Erreur inconnue dans api_signin
2023-04-09 19:04:45,457 DEBUG    > Traceback (most recent call last):
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 611, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 142, in api_signin
    result,user = sign.signin(logger=logger,mydb=mydb,email=request.json['email'],pwd=request.json['password'],debug=debug)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 540, in json
    return self.get_json()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\werkzeug\wrappers\request.py", line 571, in get_json
    return self.on_json_loading_failed(None)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\wrappers.py", line 133, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2023-04-09 19:04:46,976 DEBUG    > Requête signin.html
2023-04-09 19:04:47,342 DEBUG    > Requête projet.html
2023-04-09 19:04:48,726 DEBUG    > Requête signin.html
2023-04-09 19:05:03,985 INFO     > Lancement de l'application ! 
2023-04-09 19:05:03,985 INFO     > Création de la base de donnée
2023-04-09 19:05:03,986 INFO     > Démarrage du serveur flask
2023-04-09 19:05:10,424 DEBUG    > Requête index.html
2023-04-09 19:05:29,986 DEBUG    > Requête index.html
2023-04-09 19:34:37,857 INFO     > Lancement de l'application ! 
2023-04-09 19:34:37,858 INFO     > Création de la base de donnée
2023-04-09 19:34:37,863 INFO     > Démarrage du serveur flask
2023-04-09 19:34:41,567 DEBUG    > Requête index.html
2023-04-09 19:34:41,567 ERROR    > Erreur inconnue dans index.html
2023-04-09 19:34:41,568 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 47, in index
    return render_template('index.html', render)
TypeError: render_template() takes 1 positional argument but 2 were given

2023-04-09 19:34:43,799 DEBUG    > Requête index.html
2023-04-09 19:34:43,799 ERROR    > Erreur inconnue dans index.html
2023-04-09 19:34:43,799 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 47, in index
    return render_template('index.html', render)
TypeError: render_template() takes 1 positional argument but 2 were given

2023-04-09 19:35:13,464 INFO     > Lancement de l'application ! 
2023-04-09 19:35:13,464 INFO     > Création de la base de donnée
2023-04-09 19:35:13,465 INFO     > Démarrage du serveur flask
2023-04-09 19:35:14,959 DEBUG    > Requête index.html
2023-04-09 19:35:21,615 DEBUG    > Requête signin.html
2023-04-09 19:35:23,641 DEBUG    > Requête signup.html
2023-04-09 19:35:34,377 DEBUG    > Requête api_signup
2023-04-09 19:35:34,381 INFO     > Compte créé : Noan
2023-04-09 19:35:36,345 DEBUG    > Requête signin.html
2023-04-09 19:35:44,893 DEBUG    > Requête api_signin
2023-04-09 19:35:44,894 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:35:44,929 DEBUG    > Requête index.html
2023-04-09 19:35:59,758 DEBUG    > Requête index.html
2023-04-09 19:36:01,825 DEBUG    > Requête projet.html
2023-04-09 19:36:02,663 DEBUG    > Requête index.html
2023-04-09 19:37:07,508 INFO     > Lancement de l'application ! 
2023-04-09 19:37:07,509 INFO     > Création de la base de donnée
2023-04-09 19:37:07,510 INFO     > Démarrage du serveur flask
2023-04-09 19:37:11,219 DEBUG    > Requête index.html
2023-04-09 19:37:30,170 DEBUG    > Requête signin.html
2023-04-09 19:37:35,847 DEBUG    > Requête api_signin
2023-04-09 19:37:35,848 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:37:35,885 DEBUG    > Requête index.html
2023-04-09 19:39:07,489 INFO     > Lancement de l'application ! 
2023-04-09 19:39:07,490 INFO     > Création de la base de donnée
2023-04-09 19:39:07,490 INFO     > Démarrage du serveur flask
2023-04-09 19:39:09,936 DEBUG    > Requête index.html
2023-04-09 19:39:15,572 DEBUG    > Requête signin.html
2023-04-09 19:39:20,451 DEBUG    > Requête api_signin
2023-04-09 19:39:20,451 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:39:20,493 DEBUG    > Requête index.html
2023-04-09 19:39:49,720 INFO     > Lancement de l'application ! 
2023-04-09 19:39:49,721 INFO     > Création de la base de donnée
2023-04-09 19:39:49,721 INFO     > Démarrage du serveur flask
2023-04-09 19:39:51,797 DEBUG    > Requête index.html
2023-04-09 19:40:00,356 DEBUG    > Requête signin.html
2023-04-09 19:40:24,738 DEBUG    > Requête api_signin
2023-04-09 19:40:24,739 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:40:24,781 DEBUG    > Requête index.html
2023-04-09 19:42:05,812 INFO     > Lancement de l'application ! 
2023-04-09 19:42:05,812 INFO     > Création de la base de donnée
2023-04-09 19:42:05,813 INFO     > Démarrage du serveur flask
2023-04-09 19:42:07,378 DEBUG    > Requête index.html
2023-04-09 19:42:09,276 DEBUG    > Requête signin.html
2023-04-09 19:42:14,219 DEBUG    > Requête api_signin
2023-04-09 19:42:14,220 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:42:14,260 DEBUG    > Requête index.html
2023-04-09 19:44:44,130 INFO     > Lancement de l'application ! 
2023-04-09 19:44:44,130 INFO     > Création de la base de donnée
2023-04-09 19:44:44,131 INFO     > Démarrage du serveur flask
2023-04-09 19:44:46,077 DEBUG    > Requête index.html
2023-04-09 19:44:47,768 DEBUG    > Requête signin.html
2023-04-09 19:44:53,346 DEBUG    > Requête api_signin
2023-04-09 19:44:53,347 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:44:53,383 DEBUG    > Requête index.html
2023-04-09 19:45:43,877 INFO     > Lancement de l'application ! 
2023-04-09 19:45:43,877 INFO     > Création de la base de donnée
2023-04-09 19:45:43,878 INFO     > Démarrage du serveur flask
2023-04-09 19:45:46,410 DEBUG    > Requête index.html
2023-04-09 19:45:48,176 DEBUG    > Requête signin.html
2023-04-09 19:45:54,780 DEBUG    > Requête api_signin
2023-04-09 19:45:54,781 INFO     > Autentification validé pour : roynoan@gmail.com
2023-04-09 19:45:54,824 INFO     > Noan est connecté
2023-04-09 19:45:54,825 DEBUG    > Requête index.html
2023-04-09 19:45:59,009 DEBUG    > Requête projet.html
2023-04-09 19:45:59,929 INFO     > Noan est connecté
2023-04-09 19:45:59,930 DEBUG    > Requête index.html
2023-04-09 19:46:29,937 INFO     > Noan est connecté
2023-04-09 19:46:29,939 DEBUG    > Requête index.html
2023-04-09 19:47:00,693 DEBUG    > Requête index.html
2023-04-09 19:51:47,625 INFO     > Lancement de l'application ! 
2023-04-09 19:51:47,626 INFO     > Création de la base de donnée
2023-04-09 19:51:47,626 INFO     > Démarrage du serveur flask
2023-04-09 19:51:49,032 INFO     > Noan est connecté
2023-04-09 19:51:49,033 DEBUG    > Requête index.html
2023-04-09 19:51:54,144 DEBUG    > Requête profil.html
2023-04-09 19:51:57,416 INFO     > Noan est connecté
2023-04-09 19:51:57,417 DEBUG    > Requête index.html
2023-04-09 19:53:41,251 DEBUG    > Requête perso.html
2023-04-09 19:54:20,194 INFO     > Lancement de l'application ! 
2023-04-09 19:54:20,195 INFO     > Création de la base de donnée
2023-04-09 19:54:20,195 INFO     > Démarrage du serveur flask
2023-04-09 19:54:21,895 INFO     > Noan est connecté
2023-04-09 19:54:21,896 DEBUG    > Requête perso.html
2023-04-09 19:54:21,909 ERROR    > Erreur inconnue dans perso.html
2023-04-09 19:54:21,922 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 68, in perso
    return render_template('perso.html')
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Noan Programmation\learn\Mon site\python\templates\perso.html", line 49, in top-level template code
    {% if not render['login']%}
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'render' is undefined

2023-04-09 19:54:41,240 INFO     > Lancement de l'application ! 
2023-04-09 19:54:41,241 INFO     > Création de la base de donnée
2023-04-09 19:54:41,242 INFO     > Démarrage du serveur flask
2023-04-09 19:54:43,013 INFO     > Noan est connecté
2023-04-09 19:54:43,013 DEBUG    > Requête perso.html
2023-04-09 19:54:44,529 INFO     > Noan est connecté
2023-04-09 19:54:44,529 DEBUG    > Requête index.html
2023-04-09 19:54:46,336 INFO     > Noan est connecté
2023-04-09 19:54:46,336 DEBUG    > Requête perso.html
2023-04-09 19:54:50,004 DEBUG    > Requête profil.html
2023-04-09 19:54:51,695 INFO     > Noan est connecté
2023-04-09 19:54:51,695 DEBUG    > Requête perso.html
2023-04-09 19:54:53,089 INFO     > Noan est connecté
2023-04-09 19:54:53,089 DEBUG    > Requête index.html
2023-04-09 19:55:55,271 INFO     > Noan est connecté
2023-04-09 19:55:55,272 DEBUG    > Requête index.html
2023-04-09 19:55:59,638 INFO     > Lancement de l'application ! 
2023-04-09 19:55:59,638 INFO     > Création de la base de donnée
2023-04-09 19:55:59,639 INFO     > Démarrage du serveur flask
2023-04-09 19:56:01,380 INFO     > Noan est connecté
2023-04-09 19:56:01,381 DEBUG    > Requête index.html
2023-04-09 19:56:02,576 INFO     > Noan est connecté
2023-04-09 19:56:02,578 DEBUG    > Requête projet.html
2023-04-09 19:56:04,358 INFO     > Noan est connecté
2023-04-09 19:56:04,358 DEBUG    > Requête index.html
2023-04-09 19:56:05,900 INFO     > Noan est connecté
2023-04-09 19:56:05,900 DEBUG    > Requête projet.html
2023-04-09 19:56:07,270 INFO     > Noan est connecté
2023-04-09 19:56:07,270 DEBUG    > Requête index.html
2023-04-09 19:56:10,720 INFO     > Noan est connecté
2023-04-09 19:56:10,720 DEBUG    > Requête projet.html
2023-04-09 19:56:24,640 INFO     > Noan est connecté
2023-04-09 19:56:24,641 DEBUG    > Requête projet.html
2023-04-09 19:56:25,556 INFO     > Noan est connecté
2023-04-09 19:56:25,556 DEBUG    > Requête index.html
2023-04-09 19:56:30,659 INFO     > Noan est connecté
2023-04-09 19:56:30,660 DEBUG    > Requête index.html
2023-04-09 19:56:35,414 INFO     > Noan est connecté
2023-04-09 19:56:35,415 DEBUG    > Requête index.html
2023-04-09 19:56:40,473 INFO     > Noan est connecté
2023-04-09 19:56:40,474 DEBUG    > Requête projet.html
2023-04-09 19:57:03,679 INFO     > Noan est connecté
2023-04-09 19:57:03,679 DEBUG    > Requête index.html
2023-04-09 19:57:26,365 INFO     > Noan est connecté
2023-04-09 19:57:26,366 DEBUG    > Requête index.html
2023-04-09 19:58:13,841 INFO     > Noan est connecté
2023-04-09 19:58:13,842 DEBUG    > Requête index.html
2023-04-09 19:58:15,758 DEBUG    > Requête profil.html
2023-04-09 19:58:15,761 ERROR    > Erreur inconnue dans profil.html
2023-04-09 19:58:15,765 DEBUG    > Traceback (most recent call last):
  File "D:\Noan Programmation\learn\Mon site\python\server.py", line 122, in profil
    return render_template('profil.html')
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Noan Programmation\learn\Mon site\python\templates\profil.html", line 48, in top-level template code
    {% if not render['login']%}
  File "C:\Users\door7\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'render' is undefined

2023-04-09 19:58:45,648 INFO     > Lancement de l'application ! 
2023-04-09 19:58:45,648 INFO     > Création de la base de donnée
2023-04-09 19:58:45,649 INFO     > Démarrage du serveur flask
2023-04-09 19:58:50,468 INFO     > Noan est connecté
2023-04-09 19:58:50,468 DEBUG    > Requête profil.html
2023-04-09 19:59:42,067 INFO     > Noan est connecté
2023-04-09 19:59:42,068 DEBUG    > Requête profil.html
2023-04-09 19:59:50,829 INFO     > Noan est connecté
2023-04-09 19:59:50,829 DEBUG    > Requête profil.html
2023-04-09 19:59:57,284 INFO     > Noan est connecté
2023-04-09 19:59:57,284 DEBUG    > Requête profil.html
2023-04-09 20:00:20,021 INFO     > Noan est connecté
2023-04-09 20:00:20,021 DEBUG    > Requête profil.html
2023-04-09 20:00:47,432 INFO     > Noan est connecté
2023-04-09 20:00:47,435 DEBUG    > Requête profil.html
2023-04-09 20:00:58,931 INFO     > Noan est connecté
2023-04-09 20:00:58,931 DEBUG    > Requête profil.html
2023-04-09 20:01:04,810 INFO     > Noan est connecté
2023-04-09 20:01:04,812 DEBUG    > Requête profil.html
2023-04-09 20:01:14,482 INFO     > Noan est connecté
2023-04-09 20:01:14,483 DEBUG    > Requête profil.html
2023-04-09 20:01:20,513 INFO     > Noan est connecté
2023-04-09 20:01:20,513 DEBUG    > Requête profil.html
2023-04-09 20:01:25,636 INFO     > Noan est connecté
2023-04-09 20:01:25,637 DEBUG    > Requête profil.html
2023-04-09 20:01:40,839 INFO     > Noan est connecté
2023-04-09 20:01:40,841 DEBUG    > Requête profil.html
2023-04-09 20:02:00,191 INFO     > Noan est connecté
2023-04-09 20:02:00,192 DEBUG    > Requête profil.html
2023-04-09 20:02:12,254 INFO     > Noan est connecté
2023-04-09 20:02:12,254 DEBUG    > Requête profil.html
2023-04-09 20:03:52,341 INFO     > Noan est connecté
2023-04-09 20:03:52,342 DEBUG    > Requête profil.html
2023-04-09 20:03:57,703 INFO     > Lancement de l'application ! 
2023-04-09 20:03:57,703 INFO     > Création de la base de donnée
2023-04-09 20:03:57,704 INFO     > Démarrage du serveur flask
2023-04-09 20:03:59,359 INFO     > Noan est connecté
2023-04-09 20:03:59,360 DEBUG    > Requête profil.html
2023-04-09 20:04:11,970 INFO     > Lancement de l'application ! 
2023-04-09 20:04:11,970 INFO     > Création de la base de donnée
2023-04-09 20:04:11,972 INFO     > Démarrage du serveur flask
2023-04-09 20:04:13,731 INFO     > Noan est connecté
2023-04-09 20:04:13,733 DEBUG    > Requête profil.html
2023-04-09 20:04:45,791 INFO     > Lancement de l'application ! 
2023-04-09 20:04:45,792 INFO     > Création de la base de donnée
2023-04-09 20:04:45,792 INFO     > Démarrage du serveur flask
2023-04-09 20:04:47,686 INFO     > Noan est connecté
2023-04-09 20:04:47,687 DEBUG    > Requête profil.html
2023-04-09 20:05:16,729 INFO     > Lancement de l'application ! 
2023-04-09 20:05:16,729 INFO     > Création de la base de donnée
2023-04-09 20:05:16,730 INFO     > Démarrage du serveur flask
2023-04-09 20:05:18,970 INFO     > Noan est connecté
2023-04-09 20:05:18,970 DEBUG    > Requête profil.html
2023-04-09 20:07:34,535 INFO     > Noan est connecté
2023-04-09 20:07:34,537 DEBUG    > Requête profil.html
2023-04-09 20:07:34,537 INFO     > Noan est connecté
2023-04-09 20:07:34,538 INFO     > Noan est connecté
2023-04-09 20:07:34,538 DEBUG    > Requête index.html
2023-04-09 20:07:34,539 DEBUG    > Requête index.html
2023-04-09 20:07:40,451 INFO     > Lancement de l'application ! 
2023-04-09 20:07:40,451 INFO     > Création de la base de donnée
2023-04-09 20:07:40,452 INFO     > Démarrage du serveur flask
2023-04-09 20:07:42,253 INFO     > Noan est connecté
2023-04-09 20:07:42,254 DEBUG    > Requête index.html
2023-04-09 20:07:45,420 INFO     > Noan est connecté
2023-04-09 20:07:45,420 DEBUG    > Requête profil.html
2023-04-09 20:07:46,785 INFO     > Noan est connecté
2023-04-09 20:07:46,786 DEBUG    > Requête index.html
2023-04-09 20:07:47,969 INFO     > Noan est connecté
2023-04-09 20:07:47,970 DEBUG    > Requête perso.html
2023-04-09 20:07:53,324 INFO     > Noan est connecté
2023-04-09 20:07:53,325 DEBUG    > Requête index.html
2023-04-09 20:07:57,244 INFO     > Noan est connecté
2023-04-09 20:07:57,245 DEBUG    > Requête index.html
2023-04-09 20:07:58,007 INFO     > Noan est connecté
2023-04-09 20:07:58,007 DEBUG    > Requête projet.html
2023-04-09 20:08:01,384 INFO     > Noan est connecté
2023-04-09 20:08:01,385 DEBUG    > Requête index.html
2023-04-09 20:08:28,942 INFO     > Noan est connecté
2023-04-09 20:08:28,947 DEBUG    > Requête index.html
2023-04-09 20:09:21,054 INFO     > Noan est connecté
2023-04-09 20:09:21,055 DEBUG    > Requête index.html
2023-04-09 20:10:09,186 INFO     > Noan est connecté
2023-04-09 20:10:09,186 DEBUG    > Requête profil.html
2023-04-09 20:17:55,168 INFO     > Noan est connecté
2023-04-09 20:17:55,168 DEBUG    > Requête index.html
2023-04-09 20:21:11,795 INFO     > Lancement de l'application ! 
2023-04-09 20:21:11,796 INFO     > Création de la base de donnée
2023-04-09 20:21:11,797 INFO     > Démarrage du serveur flask
2023-04-09 20:21:13,574 INFO     > Noan est connecté
2023-04-09 20:21:13,575 DEBUG    > Requête index.html
2023-04-09 20:21:47,144 INFO     > Noan est connecté
2023-04-09 20:21:47,145 DEBUG    > Requête index.html
2023-04-09 20:21:49,442 INFO     > Noan est connecté
2023-04-09 20:21:49,442 DEBUG    > Requête editprofil.html
2023-04-09 20:21:54,219 INFO     > Noan est connecté
2023-04-09 20:21:54,219 DEBUG    > Requête profil.html
2023-04-09 20:21:55,885 INFO     > Noan est connecté
2023-04-09 20:21:55,885 DEBUG    > Requête editprofil.html
